version = "1.0"

[main]
name = "GitLab configuration"

    [main.users]
    name = "External users"

        [main.users.use_web_account]
        ask = "Authorized external user creation?"
        type = "boolean"

    [main.pages]
    name = "GitLab Pages"

        [main.pages.pages_url]
        ask = "Domain for GitLab Pages (leave empty to disable)"
        type = "string"
        optional = true
        help = "GitLab Pages allows you to publish static websites directly from a repository. Requires a dedicated domain."