test_format = 1.0

[default]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.a2faefc.name = "Upgrade from 17.11.1"

[pages]
    args.pages_enable = "true"
    args.pages_url = "domain.tld"

    only = ["install.root"]

[enterprise]
    args.gitlab_edition = "Enterprise"

    only = ["install.root"]